CREATE TABLE IF NOT EXISTS public.vacancies
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    vacancy_public_id character varying(255),
    company_name character varying(255) NOT NULL,
    company_url character varying(255) NOT NULL,
    description text NOT NULL,
    job_title character varying(255) NOT NULL,
    logo_link character varying(255) NOT NULL,
    posted_date bigint NOT NULL,
    CONSTRAINT pk_vacancies_id PRIMARY KEY (id),
    CONSTRAINT uk_vacancies_vacancy_public_id UNIQUE (company_url)
    )