CREATE TABLE IF NOT EXISTS public.locations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    city character varying(50) NOT NULL,
    country character varying(50) NOT NULL,
    remote character varying(30) NOT NULL,
    public_id character varying(50) NOT NULL,
    CONSTRAINT pk_locations_id PRIMARY KEY (id),
    CONSTRAINT uk_locations_city_remote UNIQUE (city, remote),
    CONSTRAINT uk_locations_public_id UNIQUE (city, remote)
    )